<?php
$end=100;
$array=array();
$array[0][1]="fizz";
$array[1][0]="buzz";
$array[0][0]="fizzbuzz";
for($i=1;$i<=$end;$i++) 
{
	$array[1][1]=$i;
	$fizz=ceil(($i%3)/$end);
	$buzz=ceil(($i%5)/$end);
	echo("<li>".$array[$fizz][$buzz]);
}
?>